name: test

on:
  push:
    branches: [main]
  pull_request:

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.12] # extend if needed

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
      - name: Use Node.js
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version: "18.x"
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1 # v6.3.0
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .[test]
      - name: Install SMART sandbox
        run: |
          git clone https://github.com/smart-on-fhir/smart-launcher-v2.git
          cd smart-launcher-v2
          git switch -c aa0f3b1 # Fix the version we use for the sandbox
          npm ci
          npm run build
      - name: Run tests
        run: |
          pytest tests/
        env:
          SANDBOX_DIR: ${{ github.workspace }}/smart-launcher-v2
